spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRE_HOST:localhost}:${DB_POSTGRE_PORT:5432}/postgres?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_POSTGRE_USERNAME:postgres}
    password: ${DB_POSTGRE_PASSWORD:root}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: HikariUserCP
      connectionTimeout: 30000
      connection-test-query: SELECT 1 as test
      transaction-isolation: TRANSACTION_READ_COMMITTED
    tomcat:
      test-while-idle: true
      validation-query: 1

  jpa:
    properties:
      hibernate:
        default_schema: 'msorder'
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          fetch_size: 2000
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/liquibase/master.xml
    database-change-log-table: msorderchangelog
    database-change-log-lock-table: msorderchangeloglock
    enabled: true